MNT: Pin PyInstaller==6.9 where Linux build still execs
PyInstaller 6.10+ results in:

	Traceback (most recent call last):
	  File "run.py", line 2, in <module>
		import efck.__main__
	  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
	  File "efck/__main__.py", line 61, in <module>
		main()
	  File "efck/__main__.py", line 53, in main
		from .config import load_config
	  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
	  File "efck/config.py", line 6, in <module>
		from .tabs import EmojiTab
	ImportError: cannot import name 'EmojiTab' from 'efck.tabs' (dist/efck-chat-keyboard/_internal/efck/tabs/__init__.pyc)
	[PYI-2785842:ERROR] Failed to execute script 'run' due to unhandled exception!