ENH: RPM spec file for Fedora (#4)
* MNT: Add RPM spec

Co-authored-by: Jaka Hudoklin <jaka@x-truder.net>

* fixup! MNT: Add RPM spec

* Use `git describe --abrev=0`

* Try `make srpm` build with .copr/Makefile

* Extract version string from GitHub API. Nothing else works! 🫣

* Write app_version into specfile before building

* Remove %generate_buildrequires line that errors

	Executing(%generate_buildrequires): /bin/sh -e /var/tmp/rpm-tmp.ZG7Ec0
	+ umask 022
	+ cd /builddir/build/BUILD/efck-chat-keyboard-1.0-build
	+ cd efck-chat-keyboard-1.0
	/var/tmp/rpm-tmp.ZG7Ec0: line 34: cd: efck-chat-keyboard-1.0: No such file or directory
	error: Bad exit status from /var/tmp/rpm-tmp.ZG7Ec0 (%generate_buildrequires)

* Revision after having rtfm

* Fix some names

* Unify names 😵‍💫

* %pyproject_wheel needs %generate_buildrequires

* For %check, BuildRequire pyqt6 which is not in setup_requires=

* pyproject_buildrequires -r requirements.txt

* Disable %check (crashes)

* Reshuffle files

* Avoid warnings "File listed twice"

* Avoid `find-debuginfo -S debugsourcefiles.list` error

---------

Co-authored-by: Jaka Hudoklin <jaka@x-truder.net>